### ISSUE TITLE
Error: promisify is not a function

### ISSUE THREAD

**Issue by NuroDev** [Kikobeats/is-all-reachable#7]
On load I get the following error. Not sure if an issue on my end or an issue with the module itself.
Any help would be appreciated.
`Uncaught TypeError: promisify is not a function`
`node_modules/is-all-reachable/index.js:8 Uncaught TypeError: promisify is not a function`

**Comment by Kikobeats** [comment]
Thanks for report it!

This happens because `promisy` is available under node 8 or higher.

I updated `package.json`properly https://github.com/Kikobeats/is-all-reachable/blob/master/package.json#L54

**Comment by NuroDev** [comment]
Thanks for the quick reply and quick fix.
However I've updated to version `1.1.3` and still having the same issue.
Tested on 2 separate systems, one running node version `8.2.1` and another running `6.11.0`, still same error.

**Comment by Kikobeats** [comment]
Humm, probably you are missing something, because test build is running at node 8 and all tests are green:

https://travis-ci.org/Kikobeats/is-all-reachable 

Can you try print `node --version` before use the dependency and be sure that is `>=8`?

**Comment by NuroDev** [comment]
Printed the node version and returns version `7.4.0`. So one of the modules I am using is still using node `<=8`.
